#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryosuke Naka<uchuutarou114@gmail.com>
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)


print(ans)

